-- Supabase SQL Editor에서 전체 실행하세요.
-- 여러 번 실행해도 안전하도록(idempotent) 작성되어 있어, 기존 프로젝트를 업그레이드할 때도
-- 이 파일 전체를 다시 실행하면 됩니다.
create extension if not exists btree_gist;

create table if not exists public.users (
  student_id text primary key,
  password_hash text not null,
  name text,
  is_admin boolean not null default false,
  is_active boolean not null default true,
  suspend_until timestamptz
);

alter table public.users add column if not exists must_change_password boolean not null default false;
alter table public.users add column if not exists failed_attempts integer not null default 0;
alter table public.users add column if not exists locked_until timestamptz;
alter table public.users add column if not exists created_at timestamptz not null default now();

create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true
);

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  student_id text not null references public.users(student_id) on update cascade on delete cascade,
  room_id bigint not null references public.rooms(id),
  res_date date not null,
  start_slot integer not null check (start_slot between 0 and 47),
  end_slot integer not null check (end_slot between 1 and 48 and end_slot > start_slot),
  status text not null default 'active' check (status in ('active', 'cancelled')),
  created_at timestamptz not null default now()
);

alter table public.reservations add column if not exists cancelled_at timestamptz;
alter table public.reservations add column if not exists cancelled_by text;

-- 사용자 삭제 시 예약도 함께 삭제되도록 외래키를 갱신합니다(기존 프로젝트 업그레이드용).
alter table public.reservations drop constraint if exists reservations_student_id_fkey;
alter table public.reservations
  add constraint reservations_student_id_fkey
  foreign key (student_id) references public.users(student_id)
  on update cascade on delete cascade;

create index if not exists reservations_student_date_idx
  on public.reservations (student_id, res_date)
  where status = 'active';

create table if not exists public.settings (
  key text primary key,
  value text
);

-- '로그인 상태 유지'용 세션. 토큰 원문은 저장하지 않고 SHA-256 해시만 저장합니다.
create table if not exists public.user_sessions (
  token_hash text primary key,
  student_id text not null references public.users(student_id) on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists user_sessions_student_idx on public.user_sessions (student_id);

insert into public.rooms(name, is_active) values
  ('스터디룸 1', true),
  ('스터디룸 2', true)
on conflict (name) do nothing;

insert into public.settings(key, value) values
  ('global_lock', '0'),
  ('announcement', '제2의학관 스터디룸 예약 시스템에 오신 것을 환영합니다.'),
  ('logo_url', ''),
  ('booking_window_days', '7'),
  ('daily_limit_slots', '4'),
  ('open_slot', '0'),
  ('close_slot', '48')
on conflict (key) do nothing;

-- 같은 방·날짜에서 활성 예약 시간이 겹치는 것을 DB 수준에서 차단합니다.
do $$
begin
  if not exists (
    select 1 from pg_constraint
     where conname = 'reservations_no_overlap'
       and conrelid = 'public.reservations'::regclass
  ) then
    alter table public.reservations
      add constraint reservations_no_overlap
      exclude using gist (
        room_id with =,
        res_date with =,
        int4range(start_slot, end_slot, '[)') with &&
      ) where (status = 'active');
  end if;
end $$;

-- settings 값을 정수로 읽습니다. 값이 없거나 숫자가 아니면 기본값을 씁니다.
create or replace function public.setting_int(p_key text, p_default integer)
returns integer
language plpgsql
stable
set search_path = public
as $$
declare
  v_value text;
begin
  select value into v_value from public.settings where key = p_key;
  return coalesce(nullif(trim(v_value), '')::integer, p_default);
exception
  when invalid_text_representation then
    return p_default;
end;
$$;

-- 슬롯 1칸 = 30분 (app의 SLOT_MINUTES 와 같아야 합니다)
create or replace function public.book_room(
  p_student_id text,
  p_room_id bigint,
  p_res_date date,
  p_start_slot integer,
  p_units integer
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.users%rowtype;
  v_room public.rooms%rowtype;
  v_used integer;
  v_end integer := p_start_slot + p_units;
  v_today date := (now() at time zone 'Asia/Seoul')::date;
  v_window integer := least(greatest(public.setting_int('booking_window_days', 7), 1), 30);
  v_limit integer := least(greatest(public.setting_int('daily_limit_slots', 4), 1), 48);
  v_open integer := least(greatest(public.setting_int('open_slot', 0), 0), 47);
  v_close integer := least(greatest(public.setting_int('close_slot', 48), 1), 48);
  v_start_at timestamptz;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_student_id || ':' || p_res_date::text, 0));

  if v_close <= v_open then
    v_open := 0;
    v_close := 48;
  end if;

  if coalesce((select value from public.settings where key='global_lock'), '0') = '1' then
    return jsonb_build_object('ok', false, 'message', '현재 관리자에 의해 전체 예약이 제한되어 있습니다.');
  end if;

  select * into v_user from public.users where student_id = p_student_id;
  if not found or not v_user.is_active then
    return jsonb_build_object('ok', false, 'message', '승인되지 않은 계정입니다.');
  end if;
  if v_user.suspend_until is not null and v_user.suspend_until > now() then
    return jsonb_build_object('ok', false, 'message', '이용이 일시 정지된 계정입니다.');
  end if;

  select * into v_room from public.rooms where id = p_room_id and is_active = true;
  if not found then
    return jsonb_build_object('ok', false, 'message', '선택한 스터디룸을 사용할 수 없습니다.');
  end if;

  if p_units < 1 or p_units > v_limit or p_start_slot < v_open or v_end > v_close then
    return jsonb_build_object('ok', false, 'message', '예약 시간 범위가 올바르지 않습니다.');
  end if;
  if p_res_date < v_today or p_res_date > v_today + (v_window - 1) then
    return jsonb_build_object('ok', false, 'message', format('예약은 오늘부터 %s일 이내만 가능합니다.', v_window));
  end if;

  v_start_at := ((p_res_date::timestamp + make_interval(mins => p_start_slot * 30)) at time zone 'Asia/Seoul');
  if v_start_at <= now() then
    return jsonb_build_object('ok', false, 'message', '이미 시작된 시간은 예약할 수 없습니다.');
  end if;

  select coalesce(sum(end_slot - start_slot), 0)
    into v_used
    from public.reservations
   where student_id = p_student_id and res_date = p_res_date and status = 'active';
  if v_used + p_units > v_limit then
    return jsonb_build_object(
      'ok', false,
      'message', format(
        '하루 최대 %s까지 예약할 수 있습니다.',
        case
          when v_limit % 2 = 0 then (v_limit / 2) || '시간'
          when v_limit = 1 then '30분'
          else (v_limit / 2) || '시간 30분'
        end
      )
    );
  end if;

  if exists (
    select 1 from public.reservations
     where student_id = p_student_id and room_id = p_room_id
       and res_date = p_res_date and status = 'active'
  ) and not exists (
    select 1 from public.reservations
     where student_id = p_student_id and room_id = p_room_id
       and res_date = p_res_date and status = 'active'
       and (end_slot = p_start_slot or start_slot = v_end)
  ) then
    return jsonb_build_object('ok', false, 'message', '같은 방의 추가 예약은 기존 예약과 붙어 있어야 합니다.');
  end if;

  insert into public.reservations(student_id, room_id, res_date, start_slot, end_slot)
  values (p_student_id, p_room_id, p_res_date, p_start_slot, v_end);

  return jsonb_build_object('ok', true, 'message', '예약이 완료되었습니다.');
exception
  when exclusion_violation then
    return jsonb_build_object('ok', false, 'message', '이미 예약된 시간과 겹칩니다.');
  when others then
    -- 원인을 Supabase Postgres 로그에 남기고, 사용자에게는 일반 메시지만 돌려줍니다.
    raise warning 'book_room failed [%]: %', sqlstate, sqlerrm;
    return jsonb_build_object('ok', false, 'message', '예약 처리 중 오류가 발생했습니다.');
end;
$$;

create or replace function public.cancel_reservation(
  p_reservation_id bigint,
  p_actor_id text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor public.users%rowtype;
  v_res public.reservations%rowtype;
  v_start_at timestamptz;
begin
  select * into v_actor from public.users where student_id = p_actor_id;
  if not found or not v_actor.is_active then
    return jsonb_build_object('ok', false, 'message', '권한이 없습니다.');
  end if;

  select * into v_res from public.reservations where id = p_reservation_id for update;
  if not found or v_res.status <> 'active' then
    return jsonb_build_object('ok', false, 'message', '예약을 찾을 수 없습니다.');
  end if;

  if not v_actor.is_admin then
    if v_res.student_id <> p_actor_id then
      return jsonb_build_object('ok', false, 'message', '본인 예약만 취소할 수 있습니다.');
    end if;
    v_start_at := ((v_res.res_date::timestamp + make_interval(mins => v_res.start_slot * 30)) at time zone 'Asia/Seoul');
    if v_start_at <= now() then
      return jsonb_build_object('ok', false, 'message', '예약 시작 이후에는 취소할 수 없습니다.');
    end if;
  end if;

  update public.reservations
     set status = 'cancelled', cancelled_at = now(), cancelled_by = p_actor_id
   where id = p_reservation_id;

  return jsonb_build_object('ok', true, 'message', '예약이 취소되었습니다.');
exception
  when others then
    raise warning 'cancel_reservation failed [%]: %', sqlstate, sqlerrm;
    return jsonb_build_object('ok', false, 'message', '예약 취소 중 오류가 발생했습니다.');
end;
$$;

revoke all on function public.setting_int(text, integer) from public, anon, authenticated;
revoke all on function public.book_room(text, bigint, date, integer, integer) from public, anon, authenticated;
revoke all on function public.cancel_reservation(bigint, text) from public, anon, authenticated;
grant execute on function public.setting_int(text, integer) to service_role;
grant execute on function public.book_room(text, bigint, date, integer, integer) to service_role;
grant execute on function public.cancel_reservation(bigint, text) to service_role;

-- 브라우저의 anon key로 테이블에 직접 접근하지 못하게 하고,
-- Streamlit 서버의 service_role key만 사용합니다.
alter table public.users enable row level security;
alter table public.rooms enable row level security;
alter table public.reservations enable row level security;
alter table public.settings enable row level security;
alter table public.user_sessions enable row level security;
