-- Supabase SQL Editor에서 전체 실행하세요.
create extension if not exists btree_gist;

create table if not exists public.users (
  student_id text primary key,
  password_hash text not null,
  name text,
  is_admin boolean not null default false,
  is_active boolean not null default true,
  suspend_until timestamptz
);

create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true
);

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  student_id text not null references public.users(student_id) on update cascade,
  room_id bigint not null references public.rooms(id),
  res_date date not null,
  start_slot integer not null check (start_slot between 0 and 47),
  end_slot integer not null check (end_slot between 1 and 48 and end_slot > start_slot),
  status text not null default 'active' check (status in ('active', 'cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value text
);

insert into public.rooms(name, is_active) values
  ('스터디룸 1', true),
  ('스터디룸 2', true)
on conflict (name) do nothing;

insert into public.settings(key, value) values
  ('global_lock', '0'),
  ('announcement', '제2의학관 스터디룸 예약 시스템에 오신 것을 환영합니다.'),
  ('logo_url', '')
on conflict (key) do nothing;

-- 같은 방·날짜에서 활성 예약 시간이 겹치는 것을 DB 수준에서 차단합니다.
do $$
begin
  alter table public.reservations
    add constraint reservations_no_overlap
    exclude using gist (
      room_id with =,
      res_date with =,
      int4range(start_slot, end_slot, '[)') with &&
    ) where (status = 'active');
exception
  when duplicate_object then null;
end $$;

create or replace function public.book_room(
  p_student_id text,
  p_room_id bigint,
  p_res_date date,
  p_start_slot integer,
  p_units integer
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.users%rowtype;
  v_room public.rooms%rowtype;
  v_used integer;
  v_end integer := p_start_slot + p_units;
  v_today date := (now() at time zone 'Asia/Seoul')::date;
  v_start_at timestamptz;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_student_id || ':' || p_res_date::text, 0));

  if coalesce((select value from public.settings where key='global_lock'), '0') = '1' then
    return jsonb_build_object('ok', false, 'message', '현재 관리자에 의해 전체 예약이 제한되어 있습니다.');
  end if;

  select * into v_user from public.users where student_id = p_student_id;
  if not found or not v_user.is_active then
    return jsonb_build_object('ok', false, 'message', '승인되지 않은 계정입니다.');
  end if;
  if v_user.suspend_until is not null and v_user.suspend_until > now() then
    return jsonb_build_object('ok', false, 'message', '이용이 일시 정지된 계정입니다.');
  end if;

  select * into v_room from public.rooms where id = p_room_id and is_active = true;
  if not found then
    return jsonb_build_object('ok', false, 'message', '선택한 스터디룸을 사용할 수 없습니다.');
  end if;

  if p_units < 1 or p_units > 4 or p_start_slot < 0 or v_end > 48 then
    return jsonb_build_object('ok', false, 'message', '예약 시간 범위가 올바르지 않습니다.');
  end if;
  if p_res_date < v_today or p_res_date > v_today + 6 then
    return jsonb_build_object('ok', false, 'message', '예약은 오늘부터 7일 이내만 가능합니다.');
  end if;

  v_start_at := ((p_res_date::timestamp + make_interval(mins => p_start_slot * 30)) at time zone 'Asia/Seoul');
  if v_start_at <= now() then
    return jsonb_build_object('ok', false, 'message', '이미 시작된 시간은 예약할 수 없습니다.');
  end if;

  select coalesce(sum(end_slot - start_slot), 0)
    into v_used
    from public.reservations
   where student_id = p_student_id and res_date = p_res_date and status = 'active';
  if v_used + p_units > 4 then
    return jsonb_build_object('ok', false, 'message', '하루 최대 2시간까지 예약할 수 있습니다.');
  end if;

  if exists (
    select 1 from public.reservations
     where student_id = p_student_id and room_id = p_room_id
       and res_date = p_res_date and status = 'active'
  ) and not exists (
    select 1 from public.reservations
     where student_id = p_student_id and room_id = p_room_id
       and res_date = p_res_date and status = 'active'
       and (end_slot = p_start_slot or start_slot = v_end)
  ) then
    return jsonb_build_object('ok', false, 'message', '같은 방의 추가 예약은 기존 예약과 붙어 있어야 합니다.');
  end if;

  insert into public.reservations(student_id, room_id, res_date, start_slot, end_slot)
  values (p_student_id, p_room_id, p_res_date, p_start_slot, v_end);

  return jsonb_build_object('ok', true, 'message', '예약이 완료되었습니다.');
exception
  when exclusion_violation then
    return jsonb_build_object('ok', false, 'message', '이미 예약된 시간과 겹칩니다.');
  when others then
    return jsonb_build_object('ok', false, 'message', '예약 처리 중 오류가 발생했습니다.');
end;
$$;

revoke all on function public.book_room(text, bigint, date, integer, integer) from public;
grant execute on function public.book_room(text, bigint, date, integer, integer) to service_role;

-- 브라우저의 anon key로 테이블에 직접 접근하지 못하게 하고,
-- Streamlit 서버의 service_role key만 사용합니다.
alter table public.users enable row level security;
alter table public.rooms enable row level security;
alter table public.reservations enable row level security;
alter table public.settings enable row level security;
